apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-deployment
spec:
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
      - name: catalog
        image: nestdev/catalog:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
          - name: MongoDbSettings_Host
            value: mongodb-service
          - name: MongodbSettings__Password
            valueFrom:
              secretKeyRef:
                  name: catalog-secrets
                  key: mongodb-password
        livenessProbe:
            httpGet:
                path: /health/live
                port: 80
        readinessProbe:
            httpGet:
                path: /health/live
                port: 80
          
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service
spec:
  type: LoadBalancer
  selector:
    app: catalog
  ports:
  - port: 80
    targetPort: 80

